#!/usr/bin/php -q
<?php
# ------------------------------------------------------------------
# We offer no warantee or guarantee - use this code at your own risk!
# All code is Copyright (C) 2011, Applied Trust Engineering, Inc.
# ------------------------------------------------------------------

# https://code.google.com/apis/pagespeedonline/v1/getting_started.html
# https://code.google.com/apis/pagespeedonline/v1/reference.html

$targeturl = $argv[1];

if ( isset($argv[2]) && !empty($argv[2]) ) {
    $apikey = $argv[2];
} else {
    $apikey = 'XXX PUT GOOGLE API KEY HERE XXX';
}

$url='https://www.googleapis.com/pagespeedonline/v1/runPagespeed?key='.$apikey.'&url='.$targeturl;
$json = json_decode(`wget -q -O - "$url"`);

$status = 0;
$message = 'PageSpeed Score: '.$json->score;
$perf = 'score='.$json->score;
$perf .= ',numberResources='.$json->pageStats->numberResources;
$perf .= ', numberHosts='.$json->pageStats->numberHosts;
$perf .= ', htmlResponseBytes='.$json->pageStats->htmlResponseBytes;
$perf .= ', cssResponseBytes='.$json->pageStats->cssResponseBytes;
$perf .= ', imageResponseBytes='.$json->pageStats->imageResponseBytes;
$perf .= ', javascriptResponseBytes='.$json->pageStats->javascriptResponseBytes;

echo $message." | ".$perf."\n";
exit($status);

