#!/usr/bin/php -q
<?php
# ------------------------------------------------------------------
# We offer no warantee or guarantee - use this code at your own risk!
# All code is Copyright (C) 2013, Applied Trust Engineering, Inc.
# ------------------------------------------------------------------
putenv('AWS_RDS_HOME=/usr/local/RDSCli-1.14.001');
putenv('TZ=America/Denver');

$options = getopt("I:S:d:");
if (!isset($options["I"])) { usage(); } 
if (!isset($options["S"])) { usage(); }
if (!isset($options["d"])) { usage(); }

error_reporting(-1);

$cmd = '/usr/local/RDSCli-1.14.001/bin/rds-describe-events -I '.$options["I"].' -S '.$options["S"].' --source-type db-instance --source-identifier '.$options["d"];
$r = `$cmd`;

$result = 0;
$msg = array();
foreach (preg_split("/\n/",$r) as $line) {
	if (!preg_match("/^db-instance\s+(\S+)\s+(\S+)\s+(.*)$/",$line,$matches)) {
		continue;
	}
	$event = $matches[3];
	if (preg_match("/Backing up DB instance/",$event)) {
	} elseif (preg_match("/Finished DB Instance backup/",$event)) {
		$msg[] = $matches[1];

	} elseif (preg_match("/(DB instance created)/",$event,$matches)) {
		$msg[] = $matches[1];
		$result = 1;

	} elseif (preg_match("/(DB instance restarted)/",$event,$matches)) {
		$msg[] = $matches[1];
		$result = 2;

	} elseif (preg_match("/(Multi-AZ instance failover started)/",$event,$matches)) { 
		$msg[] = $matches[1];
		$result = 2;

	} elseif (preg_match("/(Multi-AZ instance failover completed)/",$event,$matches)) {
		$msg[] = $matches[1];
		$result = 2;

	} else {
		$msg[] = " Unknown event: ".$event." ";

		$result = 2;
	}
}

$svcname = "RDS";
if ($result==0 ){	$status = "OK";
} elseif ($result==1 ){	$status = "WARNING";
} else {		$status = "CRITICAL";
}

print $svcname." ".$status." ".join(', ',$msg)." |\n";
exit($result);

